### ISSUE TITLE
controll connected device using CEC

### ISSUE THREAD

**Issue by MichelGerding** [Sholofly/ZiggoNext#81]
I am loving this integration but i would like to controll the connected non smart display using this integration. 
primarely turning it on and of like with the right power button the the remote.

is it currently possible or would it be possible to implement.

**Comment by Sholofly** [comment]
I am afraid controlling your tv is not possible. Thats because the on, off, volume and input type buttons are using radio frequency.  Only when you set up CEC in the box settings the tv will Turn on when you turn on your box. But that's not controlled by my component. You can consider to use an RF transmitter for that kind of stuff..

**Comment by MichelGerding** [comment]
Thanks for the quick response.
do you happen to know which frequency the remote uses? is this the standard 433mhz?
lukily when looking around for that i already found a post that figured out the ir codes [link](https://community.ziggo.nl/t5/TV-Radio/Compacte-Next-IR-codes-voor-o-a-Pronto/td-p/114252)
